sudo: required
services:
    -docker

before_install:
    - docker build -t shashank7777/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shashank7777/docker-react npm run test -- --coverage
