sudo: required
services:
    -docker

before_install:
    - docker build -t shashank7777/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shashank7777/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: "docker-react"
    env: DockerReact-env
    bucket_name: elasticbeanstalk-us-east-1-761069312062
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key:
        secure: "secret_access_key"
